@startuml
actor Utilisateur
participant "CredentialsController" as CredController
participant "CredentialsService" as CredService
database "CredentialRepository" as CredRepo
database "EnvironmentRepository" as EnvRepo

Utilisateur -> CredController : POST /credentials
CredController -> CredService : create(createCredentialDto)
CredService -> EnvRepo : findOne(createCredentialDto.environmentId)
EnvRepo --> CredService : environment
CredService -> CredRepo : save(credential)
CredRepo --> CredService : credential
CredService --> CredController : credential
CredController --> Utilisateur : 201 Created (credential)
@enduml
