@startuml
actor Utilisateur
participant "EnvironmentSnapshotsController" as SnapController
participant "EnvironmentSnapshotsService" as SnapService
database "EnvironmentSnapshotRepository" as SnapRepo
database "ServiceVersionRepository" as SVRepo
database "EnvironmentRepository" as EnvRepo

Utilisateur -> SnapController : POST /environment-snapshots/{id}/restore
SnapController -> SnapService : restore(id)
SnapService -> SnapRepo : findOne(id)
SnapRepo --> SnapService : snapshot
SnapService -> SVRepo : getServiceVersions(snapshot)
SVRepo --> SnapService : serviceVersions
SnapService -> EnvRepo : updateEnvironment(serviceVersions)
SnapService --> SnapController : void
SnapController --> Utilisateur : 200 OK
@enduml
